export default function Home() {
  return (
    <main>
      <nav className="nav shell"><a className="wordmark" href="#top">MB<span>.</span>S</a><div className="nav-links"><a href="#work">Work</a><a href="#about">About</a><a href="#contact">Contact</a></div><a className="nav-cta" href="mailto:Mscott9160@outlook.com">Let&apos;s talk <span>↗</span></a></nav>
      <section className="hero shell" id="top"><div className="hero-copy reveal"><p className="eyebrow"><span className="status-dot" /> Available for meaningful work</p><h1>I build digital<br /><em>experiences</em> that<br />move people forward.</h1><p className="lede">Myles B. Scott is a software engineer and product-minded builder turning complex problems into clear, useful products.</p><div className="hero-actions"><a className="button button-primary" href="#work">Explore my work <span>↓</span></a><a className="text-link" href="/resume.pdf" target="_blank" rel="noreferrer">Resume <span>↗</span></a></div></div><div className="hero-art reveal-delay" aria-label="Abstract blue geometric portrait placeholder"><div className="art-ring ring-one" /><div className="art-ring ring-two" /><div className="art-block block-one" /><div className="art-block block-two" /><div className="art-label">MS / 01<br />ENGINEERING<br />&amp; DESIGN</div></div></section>
      <div className="signal-bar"><div className="shell signal-inner"><span>Currently focused on</span><strong>Building thoughtful software for ambitious teams</strong><span className="signal-mark">✳</span></div></div>
      <section className="work-section shell" id="work"><div className="section-heading"><p className="eyebrow">Selected work / 01</p><h2>A few things I&apos;ve<br /><em>made useful.</em></h2><p>Projects are where curiosity becomes craft. Here&apos;s a selection of work that shows how I think, build, and collaborate.</p></div><div className="project-grid"><article className="project-card project-blue"><div className="project-top"><span>01 / Product</span><span>↗</span></div><div><h3>Explore my GitHub<br /><em>in progress.</em></h3><a href="https://github.com/mscott9160-web" target="_blank" rel="noreferrer">View projects <span>↗</span></a></div></article><article className="project-card project-ink"><div className="project-top"><span>02 / Portfolio</span><span>↗</span></div><div><h3>This space is<br /><em>just beginning.</em></h3><a href="https://www.linkedin.com/in/mylesbscott/" target="_blank" rel="noreferrer">See my journey <span>↗</span></a></div></article></div></section>
      <section className="about-section shell" id="about"><div><p className="eyebrow">A little context / 02</p><h2>Technical enough<br />to go deep.<br /><em>Human enough</em><br />to zoom out.</h2></div><div className="about-copy"><p>I care about the space where technology, people, and possibility meet. My best work happens when I&apos;m learning something unfamiliar, making it legible, and helping a team ship with confidence.</p><div className="skills"><span>Software engineering</span><span>Product thinking</span><span>Systems &amp; APIs</span><span>Continuous learning</span></div><a className="button button-outline" href="https://github.com/mscott9160-web" target="_blank" rel="noreferrer">More on GitHub <span>↗</span></a></div></section>
      <section className="contact-section shell" id="contact"><p className="eyebrow">Have a good problem? / 03</p><h2>Let&apos;s make<br /><em>something matter.</em></h2><a className="contact-email" href="mailto:Mscott9160@outlook.com">Mscott9160@outlook.com <span>↗</span></a><div className="contact-meta"><span>Based in the United States</span><span>© 2026 Myles B. Scott</span><span><a href="https://www.linkedin.com/in/mylesbscott/" target="_blank" rel="noreferrer">LinkedIn</a> / <a href="https://github.com/mscott9160-web" target="_blank" rel="noreferrer">GitHub</a></span></div></section>
    </main>
  );
}
